# Generated by Django 2.1.3 on 2018-11-05 13:47

import caesar.models.product
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='none', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('reference', models.CharField(blank=True, max_length=25, null=True, validators=[caesar.models.product.validate_first_letter])),
                ('price', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('borrowed_date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(null=True, upload_to='products')),
                ('borrower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_products', to=settings.AUTH_USER_MODEL)),
                ('category', models.ManyToManyField(related_name='categories', to='caesar.Category')),
            ],
        ),
    ]
